### ISSUE TITLE
Are you using Bootstrap Grid in the website?

### ISSUE THREAD

**Issue by hendrasan** [AdamMarsden/simple-typography#2]
I noticed you're using some grid layout in the demo [website](https://adam-marsden.co.uk/simple-typography), I notice the naming convention is like Bootstrap 4. If so, what's the best way to incorporate the Bootstrap components to not break your reset and base style?

**Comment by AdamMarsden** [comment]
Hi @benhanks040888 I ONLY use the Bootstrap grid on that site, nothing else of Bootstrap though. I wouldn't recommend this over using Bootstraps typestyles if you're pulling in the whole of Bootstrap into your project.
